version: '3.9'

services:
    api-nginx:
        build: docker/api/nginx
        volumes:
            - ./api:/app
        ports:
            - '8080:80'
        restart: on-failure

    api-php-fpm:
        build: docker/api/php-fpm
        volumes:
            - ./api:/app
        restart: on-failure

    api-php-cli:
        build: docker/api/php-cli
        user: '1000:1000'
        volumes:
            - ./api:/app
        restart: on-failure

    frontend-node-cli:
        build: docker/frontend/node-cli
        user: '1000:1000'
        volumes:
            - ./frontend:/app
        restart: on-failure

    mysql:
        image: mysql:8.0.31
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: news
        restart: on-failure

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql
        ports:
            - '5000:80'
        restart: on-failure