user_controllers:
    resource:
        path: ../src/Controller/User
        namespace: App\Controller\User
    type: attribute
    prefix: api/user

admin_controllers:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: attribute
    prefix: api/admin

auth_controllers:
    resource:
        path: ../src/Controller/Auth
        namespace: App\Controller\Auth
    type: attribute
    prefix: api/auth

auth_login:
    path: /api/auth/login
    methods: 'POST'